version: '3.7'
services:
  database:
    container_name: postgres_transactions
    image: postgres:11.5
    environment:
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions123
    ports:
      - "5434:5432"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: transaction-swagger-ui
    ports:
      - "8082:8080"
    environment:
      URL: http://localhost:8080/v2/api-docs