spring:
  datasource:
    username: transactions
    password: transactions123
    url: jdbc:postgresql://localhost:5434/transactions
  jpa:
    hibernate:
      ddl-auto: create
server:
  error:
    include-message: always
    include-binding-errors: always